#include "model.h"
static int HaveAGoodDay;
namespace mm {
#line 1 "c:/users/administrator/documents/visual studio 2010/Projects/MochModel3/ModelStrings.mpp"
//LABEL(ModelStrings, EN)	Model-specific strings

/*NOTE(ModelStrings, EN)
	This module contains model-specific strings used in the progress dialog.
*/

//string S_MODEL_FINISH;		//EN Finish

//string S_MODEL_REPLICATE;	//EN Replicate

//string S_MODEL_SIMULATION;	//EN Simulation

//string S_MODEL_START;		//EN Start


} // namespace 
